// seeds/recipe_seed.js
exports.seed = function(knex) {
  return knex('RECIPE').del()
    .then(function() {
      return knex('RECIPE').insert([
        // Latte
        { BEVERAGE_SIZE_ID: 1, MATERIAL_ID: 1, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 1, MATERIAL_ID: 4, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 2, MATERIAL_ID: 1, QUANTITY: 12 },
        { BEVERAGE_SIZE_ID: 2, MATERIAL_ID: 4, QUANTITY: 6 },

        // Green Tea
        { BEVERAGE_SIZE_ID: 3, MATERIAL_ID: 8, QUANTITY: 15 },
        { BEVERAGE_SIZE_ID: 3, MATERIAL_ID: 6, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 4, MATERIAL_ID: 8, QUANTITY: 18 },
        { BEVERAGE_SIZE_ID: 4, MATERIAL_ID: 6, QUANTITY: 12 },

        // Milk Tea
        { BEVERAGE_SIZE_ID: 5, MATERIAL_ID: 9, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 5, MATERIAL_ID: 4, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 6, MATERIAL_ID: 9, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 6, MATERIAL_ID: 4, QUANTITY: 12 },

        // Orange Juice
        { BEVERAGE_SIZE_ID: 7, MATERIAL_ID: 15, QUANTITY: 25 },
        { BEVERAGE_SIZE_ID: 7, MATERIAL_ID: 16, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 8, MATERIAL_ID: 15, QUANTITY: 30 },
        { BEVERAGE_SIZE_ID: 8, MATERIAL_ID: 16, QUANTITY: 6 },

        // Espresso
        { BEVERAGE_SIZE_ID: 9, MATERIAL_ID: 1, QUANTITY: 18 },
        { BEVERAGE_SIZE_ID: 9, MATERIAL_ID: 2, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 10, MATERIAL_ID: 1, QUANTITY: 22 },
        { BEVERAGE_SIZE_ID: 10, MATERIAL_ID: 2, QUANTITY: 10 },

        // Black Coffee
        { BEVERAGE_SIZE_ID: 11, MATERIAL_ID: 2, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 11, MATERIAL_ID: 3, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 12, MATERIAL_ID: 2, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 12, MATERIAL_ID: 3, QUANTITY: 10 },

        // Oolong Tea
        { BEVERAGE_SIZE_ID: 13, MATERIAL_ID: 17, QUANTITY: 15 },
        { BEVERAGE_SIZE_ID: 13, MATERIAL_ID: 6, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 14, MATERIAL_ID: 17, QUANTITY: 18 },
        { BEVERAGE_SIZE_ID: 14, MATERIAL_ID: 6, QUANTITY: 10 },

        // Apple Juice
        { BEVERAGE_SIZE_ID: 15, MATERIAL_ID: 19, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 15, MATERIAL_ID: 16, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 16, MATERIAL_ID: 19, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 16, MATERIAL_ID: 16, QUANTITY: 6 },

        // Smoothie
        { BEVERAGE_SIZE_ID: 17, MATERIAL_ID: 20, QUANTITY: 30 },
        { BEVERAGE_SIZE_ID: 17, MATERIAL_ID: 7, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 18, MATERIAL_ID: 20, QUANTITY: 36 },
        { BEVERAGE_SIZE_ID: 18, MATERIAL_ID: 7, QUANTITY: 12 },

        // Iced Latte
        { BEVERAGE_SIZE_ID: 19, MATERIAL_ID: 1, QUANTITY: 12 },
        { BEVERAGE_SIZE_ID: 19, MATERIAL_ID: 4, QUANTITY: 6 },
        { BEVERAGE_SIZE_ID: 20, MATERIAL_ID: 1, QUANTITY: 14 },
        { BEVERAGE_SIZE_ID: 20, MATERIAL_ID: 4, QUANTITY: 7 },

        // Matcha Latte
        { BEVERAGE_SIZE_ID: 21, MATERIAL_ID: 8, QUANTITY: 15 },
        { BEVERAGE_SIZE_ID: 21, MATERIAL_ID: 4, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 22, MATERIAL_ID: 8, QUANTITY: 18 },
        { BEVERAGE_SIZE_ID: 22, MATERIAL_ID: 4, QUANTITY: 12 },

        // Lemon Tea
        { BEVERAGE_SIZE_ID: 23, MATERIAL_ID: 9, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 23, MATERIAL_ID: 6, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 24, MATERIAL_ID: 9, QUANTITY: 12 },
        { BEVERAGE_SIZE_ID: 24, MATERIAL_ID: 6, QUANTITY: 6 },

        // Pineapple Juice
        { BEVERAGE_SIZE_ID: 25, MATERIAL_ID: 15, QUANTITY: 15 },
        { BEVERAGE_SIZE_ID: 25, MATERIAL_ID: 16, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 26, MATERIAL_ID: 15, QUANTITY: 18 },
        { BEVERAGE_SIZE_ID: 26, MATERIAL_ID: 16, QUANTITY: 6 },

        // Mango Smoothie
        { BEVERAGE_SIZE_ID: 27, MATERIAL_ID: 20, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 27, MATERIAL_ID: 7, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 28, MATERIAL_ID: 20, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 28, MATERIAL_ID: 7, QUANTITY: 10 },

        // Cappuccino
        { BEVERAGE_SIZE_ID: 29, MATERIAL_ID: 1, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 29, MATERIAL_ID: 4, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 30, MATERIAL_ID: 1, QUANTITY: 12 },
        { BEVERAGE_SIZE_ID: 30, MATERIAL_ID: 4, QUANTITY: 6 },

        // Cola
        { BEVERAGE_SIZE_ID: 31, MATERIAL_ID: 15, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 31, MATERIAL_ID: 16, QUANTITY: 2 },
        { BEVERAGE_SIZE_ID: 32, MATERIAL_ID: 15, QUANTITY: 12 },
        { BEVERAGE_SIZE_ID: 32, MATERIAL_ID: 16, QUANTITY: 3 },

        // Lemon Soda
        { BEVERAGE_SIZE_ID: 33, MATERIAL_ID: 9, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 33, MATERIAL_ID: 15, QUANTITY: 4 },
        { BEVERAGE_SIZE_ID: 34, MATERIAL_ID: 9, QUANTITY: 10 },
        { BEVERAGE_SIZE_ID: 34, MATERIAL_ID: 15, QUANTITY: 5 },

        // Sparkling Water
        { BEVERAGE_SIZE_ID: 35, MATERIAL_ID: 19, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 36, MATERIAL_ID: 19, QUANTITY: 6 },

        // Mineral Water
        { BEVERAGE_SIZE_ID: 37, MATERIAL_ID: 20, QUANTITY: 5 },
        { BEVERAGE_SIZE_ID: 38, MATERIAL_ID: 20, QUANTITY: 6 },

        // Chocolate Milkshake
        { BEVERAGE_SIZE_ID: 39, MATERIAL_ID: 18, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 39, MATERIAL_ID: 7, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 40, MATERIAL_ID: 18, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 40, MATERIAL_ID: 7, QUANTITY: 10 },

        // Vanilla Milkshake
        { BEVERAGE_SIZE_ID: 41, MATERIAL_ID: 19, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 41, MATERIAL_ID: 7, QUANTITY: 8 },
        { BEVERAGE_SIZE_ID: 42, MATERIAL_ID: 19, QUANTITY: 24 },
        { BEVERAGE_SIZE_ID: 42, MATERIAL_ID: 7, QUANTITY: 10 },

        // Strawberry Milkshake
        { BEVERAGE_SIZE_ID: 43, MATERIAL_ID: 20, QUANTITY: 20 },
        { BEVERAGE_SIZE_ID: 43, MATERIAL_ID: 7, QUANTITY: 8 },
      ]);
    });
};
